server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: abcdef
    key-store-type: PKCS12
    key-alias: myapp
  compression:
    enabled: true
spring:
  messages:
    basename: "messages,config.i18n.messages"
    fallback-to-system-locale: false